DELETE http://localhost:3001/api/persons/3

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jalo Peura",
    "number": "222-222-222"
}

###

POST https://fso-q8rs.onrender.com/api/persons
Content-Type: application/json

{
    "name": "Jalo Peura",
    "number": "222-222-222"
}

###

DELETE https://fso-q8rs.onrender.com/api/persons/1